name: llm_services
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: ["gpu"]
    entrypoint: >
      sh -c "ollama serve & sleep 5 && ollama pull qwen3.5:9b && ollama pull nomic-embed-text:v1.5 && wait"
    healthcheck:
      test:
        [
          "CMD",
          "sh",
          "-c",
          "ollama list | grep qwen3.5:9b && ollama list | grep nomic-embed-text:v1.5",
        ]
      interval: 30s
      timeout: 10s
      retries: 20
    networks:
      - reverse-proxy

  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    volumes:
      - ./searxng_data:/etc/searxng:rw
    environment:
      - SEARXNG_HOSTNAME=localhost:8080/
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    networks:
      - reverse-proxy

  open-webui:
    image: ghcr.io/open-webui/open-webui:cuda
    container_name: open-webui
    ports:
      - "8091:8080"
    volumes:
      - open-webui:/app/backend/data
    environment:
      - WEBUI_AUTH=True
      - OLLAMA_BASE_URL=http://ollama:11434
      - ENABLE_WEB_SEARCH=True
      - WEB_SEARCH_ENGINE=searxng
      - SEARXNG_QUERY_URL=http://searxng:8080/search?q=<query>
      - SEARXNG_LANGUAGE=all
      - WEB_SEARCH_RESULT_COUNT=3
    depends_on:
      ollama:
        condition: service_healthy
      searxng:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 5s
      retries: 10
    networks:
      - reverse-proxy
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: ["gpu"]
  # comfyui:
  #   image: yanwk/comfyui-boot:cu124-slim
  #   container_name: comfyui
  #   ports:
  #     - "8188:8188"
  #   volumes:
  #     - ./comfyui_data/storage:/root
  #     - ./comfyui_data/models:/root/ComfyUI/models
  #     - ./comfyui_data/output:/root/ComfyUI/output
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: all
  #             capabilities: [gpu]
  #   healthcheck:
  #     test: ["CMD-SHELL", "curl -f http://localhost:8188/history || exit 1"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 60s
  #   restart: unless-stopped
  #   networks:
  #     - reverse-proxy

volumes:
  open-webui:

networks:
  reverse-proxy:
    external: true
    name: reverse_proxy_reverse-proxy
